import { ModuleData, Task } from './types';
import { Activity, BarChart3, BookOpen, Cpu, Globe, Layers, Search, Zap, Bot } from 'lucide-react';

export const MIA_MODULE: ModuleData = {
  id: 9,
  title: 'MIA: Fichas de IA',
  subtitle: 'Sugerencias Artificiales',
  levelRange: 'N/A',
  description: 'Espacio para volcar todas las fichas generadas por la IA.',
  iconName: 'Bot',
  tasks: [],
};

export const MEDIA_MODULES: ModuleData[] = [
  {
    id: 1,
    title: 'Auditoría Inicial',
    subtitle: 'Diagnóstico Técnico & Contenidos',
    levelRange: '0-20',
    description:
      'Evaluación del estado actual del medio. Detección de bloqueos de indexación y salud técnica básica.',
    iconName: 'Search',
    tasks: [
      {
        id: 'm1-1',
        title: 'Verificar Indexación (robots.txt & sitemap)',
        description:
          'Asegurar que Googlebot puede rastrear las secciones de noticias y que el sitemap.xml se actualiza en tiempo real.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm1-2',
        title: 'Auditoría HTTPS y Seguridad',
        description: 'Certificados SSL válidos y sin contenido mixto.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm1-3',
        title: 'Revisión Core Web Vitals (Móvil)',
        description: 'Validar LCP, CLS y FID en plantillas de artículo.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm1-4',
        title: 'Detección de Canibalizaciones',
        description: 'Identificar múltiples noticias compitiendo por la misma keyword.',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'm1-5',
        title: 'Estructura de URLs',
        description: 'URLs limpias, sin parámetros innecesarios y con jerarquía lógica.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm1-6',
        title: 'Auditoría de Errores de Rastreo (4xx, 5xx)',
        description: 'Identificar y corregir páginas no encontradas y errores de servidor.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm1-7',
        title: 'Revisión de Etiquetas Canonical',
        description: 'Evitar contenido duplicado técnico mediante canonicals correctos.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm1-8',
        title: 'Cabeceras de Seguridad (HSTS, CSP)',
        description: 'Implementar cabeceras para mejorar la seguridad y confianza.',
        impact: 'Medium',
        status: 'pending',
        category: 'Security',
      },
    ],
  },
  {
    id: 2,
    title: 'Estrategia & Verticales',
    subtitle: 'Definición de Objetivos',
    levelRange: '20-40',
    description:
      'Transformar el caos de publicación en una estrategia estructurada de verticales y clusters.',
    iconName: 'Layers',
    tasks: [
      {
        id: 'm2-1',
        title: 'Definir Verticales Temáticos',
        description:
          'Establecer los pilares de contenido (ej: Política, Deportes, Economía) y su peso en la home.',
        impact: 'High',
        status: 'pending',
        category: 'Strategy',
      },
      {
        id: 'm2-2',
        title: 'Keyword Research: News vs Evergreen',
        description:
          'Separar estrategia de Breaking News (Google Discover) de tráfico Evergreen (Búsqueda).',
        impact: 'High',
        status: 'pending',
        category: 'Strategy',
      },
      {
        id: 'm2-3',
        title: 'Calendario Editorial SEO',
        description: 'Planificación de eventos recurrentes (Elecciones, Black Friday, Lotería).',
        impact: 'Medium',
        status: 'pending',
        category: 'Strategy',
      },
      {
        id: 'm2-4',
        title: 'Estrategia de Clusters',
        description: 'Crear páginas pilar para temas de alto volumen y enlazar noticias satélite.',
        impact: 'Medium',
        status: 'pending',
        category: 'Strategy',
      },
    ],
  },
  {
    id: 3,
    title: 'SEO Editorial',
    subtitle: 'Workflow de Redacción',
    levelRange: '40-60',
    description: 'Integración de criterios SEO en el día a día de la redacción periodística.',
    iconName: 'BookOpen',
    tasks: [
      {
        id: 'm3-1',
        title: 'Optimización de Titulares (H1 vs Title)',
        description: 'Diferenciar titular editorial (atractivo) del Title Tag (buscable).',
        impact: 'High',
        status: 'pending',
        category: 'Editorial',
      },
      {
        id: 'm3-2',
        title: 'Estructura de Entradilla',
        description: 'Responder a las 5W en el primer párrafo incluyendo keywords principales.',
        impact: 'High',
        status: 'pending',
        category: 'Editorial',
      },
      {
        id: 'm3-3',
        title: 'Datos Estructurados (NewsArticle)',
        description: 'Implementar Schema.org para asegurar aparición en carruseles de noticias.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm3-4',
        title: 'Optimización de Imágenes (Alt & Caption)',
        description: 'Descripciones precisas y pies de foto informativos.',
        impact: 'Low',
        status: 'pending',
        category: 'Editorial',
      },
      {
        id: 'm3-5',
        title: 'Enlazado Interno Contextual',
        description: 'Relacionar la noticia con el contexto previo del tema.',
        impact: 'Medium',
        status: 'pending',
        category: 'Editorial',
      },
      {
        id: 'm3-6',
        title: 'Auditoría de Contenido Duplicado y Thin Content',
        description: 'Detectar y mejorar noticias con poco contenido o copiadas.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'm3-7',
        title: 'Revisión Meta Tags Completos',
        description: 'Optimización de Title, Description, y tags sociales (OG, Twitter).',
        impact: 'Medium',
        status: 'pending',
        category: 'Editorial',
      },
    ],
  },
  {
    id: 4,
    title: 'Técnico Avanzado',
    subtitle: 'Discover & Rendimiento',
    levelRange: '60-75',
    description: 'Optimización profunda para Google Discover, News y Crawl Budget.',
    iconName: 'Cpu',
    tasks: [
      {
        id: 'm4-1',
        title: 'Optimización para Google Discover',
        description:
          'Imágenes de alta resolución (min 1200px), títulos emotivos pero no clickbait.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm4-2',
        title: 'Gestión de Crawl Budget',
        description: 'Bloquear parámetros de tracking, filtros de búsqueda interna y tags vacíos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm4-3',
        title: 'AMP o Core Web Vitals Óptimos',
        description: 'Asegurar carga instantánea en redes móviles inestables.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm4-4',
        title: 'Gestión de Paginaciones',
        description: 'Implementar rel=next/prev correctamente en categorías.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm4-5',
        title: 'Validación W3C y Semántica HTML5',
        description: 'Corregir errores de código y asegurar uso correcto de etiquetas HTML5.',
        impact: 'Low',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'm4-6',
        title: 'Auditoría de Enlaces Salientes Rotos',
        description: 'Evitar mala experiencia de usuario corrigiendo enlaces externos rotos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Maintenance',
      },
      {
        id: 'm4-7',
        title: 'Compatibilidad de Navegadores y Renderizado',
        description: 'Verificar correcta visualización en diversos navegadores y dispositivos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 5,
    title: 'Autoridad & E-E-A-T',
    subtitle: 'Confianza y Marca',
    levelRange: '75-85',
    description: 'Consolidar al medio y sus periodistas como fuentes fidedignas.',
    iconName: 'Activity',
    tasks: [
      {
        id: 'm5-1',
        title: 'Páginas de Autor Completas',
        description: 'Bios detalladas, enlaces a RRSS, y listado de artículos por periodista.',
        impact: 'High',
        status: 'pending',
        category: 'Authority',
      },
      {
        id: 'm5-2',
        title: 'Política Editorial Visible',
        description: 'Página clara sobre ética, financiación y procesos de corrección.',
        impact: 'Medium',
        status: 'pending',
        category: 'Authority',
      },
      {
        id: 'm5-3',
        title: 'Citación de Fuentes Primarias',
        description: 'Enlazar a estudios, leyes o fuentes originales en el cuerpo de la noticia.',
        impact: 'Medium',
        status: 'pending',
        category: 'Editorial',
      },
    ],
  },
  {
    id: 6,
    title: 'Distribución & Enlaces',
    subtitle: 'Amplificación',
    levelRange: '85-95',
    description: 'Estrategias off-page para aumentar la referencia del dominio.',
    iconName: 'Globe',
    tasks: [
      {
        id: 'm6-1',
        title: 'Estrategia de Sindicación',
        description: 'Controlar canonicals en contenido compartido con otros medios del grupo.',
        impact: 'High',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'm6-2',
        title: 'Recuperación de Enlaces',
        description: 'Detectar menciones de marca sin enlace y solicitar la atribución.',
        impact: 'Low',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'm6-3',
        title: 'Newsletter & Push Notifications',
        description:
          '### Tarea: "Newsletter & Push Notifications"\n\n#### Por qué es crítica:\n- La Newsletter y las Push Notifications son fundamentales para mantener una audiencia comprometida y recurrente en un medio de comunicación.\n\n#### Micro-Guía de Ejecución:\n- Diseña contenido atractivo y relevante para tus suscriptores.\n- Segmenta tu audiencia para enviar mensajes personalizados.\n- Usa herramientas de automatización para programar envíos regulares.\n- Analiza métricas de apertura y clics para optimizar tus estrategias.\n\n#### Pro Tip:\n- Personaliza tus mensajes tanto como sea posible, mostrando a tu audiencia que valoras su tiempo y preferencias.\n\n#### Herramienta sugerida:\n- Para analizar métricas de apertura y clics, utiliza herramientas como Google Analytics o plataformas de email marketing como Mailchimp.',
        impact: 'Medium',
        status: 'pending',
        category: 'Distribution',
      },
      {
        id: 'm6-4',
        title: 'Auditoría de Textos Ancla (Anchors)',
        description: 'Analizar distribución de anchors para evitar sobre-optimización.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'm6-5',
        title: 'Identificación de Backlinks Perdidos',
        description: 'Monitorear y recuperar enlaces entrantes que se han perdido.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
    ],
  },
  {
    id: 7,
    title: 'Mejora Continua',
    subtitle: 'Analítica & KPIs',
    levelRange: '95-100',
    description: 'El SEO como sistema vivo basado en datos.',
    iconName: 'BarChart3',
    tasks: [
      {
        id: 'm7-1',
        title: 'Dashboard de Rendimiento en Tiempo Real',
        description: 'Monitorización de tráfico Discover vs Search.',
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
      {
        id: 'm7-2',
        title: 'Análisis de Decadencia (Content Decay)',
        description: 'Identificar artículos evergreen que pierden tráfico para actualizarlos.',
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
      {
        id: 'm7-3',
        title: 'Alertas Técnicas Automatizadas',
        description: 'Sistema de aviso ante caídas de servidor o errores 404 masivos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 8,
    title: 'Extras & Consultas',
    subtitle: 'Acciones Adicionales',
    levelRange: '100+',
    description:
      'Espacio para añadir acciones personalizadas y consultas específicas que surjan durante el proyecto.',
    iconName: 'Sparkles',
    isCustom: true,
    tasks: [],
  },
  MIA_MODULE,
];

export const ECOMMERCE_MODULES: ModuleData[] = [
  {
    id: 1,
    title: 'Arquitectura Técnica',
    subtitle: 'Cimientos del Ecommerce',
    levelRange: '0-20',
    description: 'Configuración esencial para tiendas online. Indexación y control de facetas.',
    iconName: 'Search',
    tasks: [
      {
        id: 'e1-1',
        title: 'Control de Facetas y Filtros',
        description: 'Configurar canonicals o noindex en combinaciones de filtros infinitas.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e1-2',
        title: 'Sitemap de Productos y Categorías',
        description: 'Sitemaps separados para productos y categorías prioritarias.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e1-3',
        title: 'Estructura de URLs Amigable',
        description: 'URLs lógicas (/categoria/producto) evitando IDs excesivos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e1-4',
        title: 'Velocidad de Carga (CWV)',
        description: 'Optimización crítica de LCP en fichas de producto.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e1-5',
        title: 'Auditoría de Errores de Rastreo (4xx, 5xx)',
        description: 'Eliminar errores que afecten al presupuesto de rastreo de productos.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e1-6',
        title: 'Cabeceras de Seguridad y HTTPS',
        description: 'Asegurar transacciones con HSTS y seguridad estricta.',
        impact: 'High',
        status: 'pending',
        category: 'Security',
      },
      {
        id: 'e1-7',
        title: 'Gestión de Redirecciones 301',
        description: 'Manejo correcto de productos discontinuados o movidos.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 2,
    title: 'Estructura de Catálogo',
    subtitle: 'Jerarquía y Navegación',
    levelRange: '20-40',
    description: 'Organización lógica del inventario para usuarios y bots.',
    iconName: 'Layers',
    tasks: [
      {
        id: 'e2-1',
        title: 'Árbol de Categorías Optimizado',
        description: 'Investigación de palabras clave para nombrar categorías.',
        impact: 'High',
        status: 'pending',
        category: 'Strategy',
      },
      {
        id: 'e2-2',
        title: 'Migas de Pan (Breadcrumbs)',
        description: 'Navegación clara y marcada con Schema.',
        impact: 'Medium',
        status: 'pending',
        category: 'Structure',
      },
      {
        id: 'e2-3',
        title: 'Gestión de Productos Agotados',
        description: 'Estrategia para productos fuera de stock (alternativas, 301, o aviso).',
        impact: 'Medium',
        status: 'pending',
        category: 'Strategy',
      },
      {
        id: 'e2-4',
        title: 'Paginaciones en Categorías',
        description: 'Optimización de paginación para rastreo profundo de productos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 3,
    title: 'SEO On-Page Fichas',
    subtitle: 'Conversión y Tráfico',
    levelRange: '40-60',
    description: 'Optimización de la página de producto individual.',
    iconName: 'BookOpen',
    tasks: [
      {
        id: 'e3-1',
        title: 'Descripciones de Producto Únicas',
        description: 'Evitar contenido duplicado del fabricante. Textos originales.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'e3-2',
        title: 'Schema Product & Offer',
        description: 'Datos estructurados para precio, stock y valoraciones (Rich Snippets).',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e3-3',
        title: 'Optimización de Imágenes de Producto',
        description: 'Compresión, formato WebP y atributos ALT descriptivos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'e3-4',
        title: 'Validación HTML5 y Semántica',
        description: 'Estructura de código limpia para mejor interpretación.',
        impact: 'Low',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'e3-5',
        title: 'Auditoría de Enlaces Salientes Rotos',
        description: 'Verificar que enlaces a manuales o externos funcionen.',
        impact: 'Low',
        status: 'pending',
        category: 'Maintenance',
      },
    ],
  },
  {
    id: 4,
    title: 'Estrategia de Contenidos',
    subtitle: 'Blog y Guías de Compra',
    levelRange: '60-75',
    description: 'Captación de tráfico top-of-funnel.',
    iconName: 'Cpu',
    tasks: [
      {
        id: 'e4-1',
        title: 'Guías de Compra y Comparativas',
        description: 'Contenido informacional que enlace a productos.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'e4-2',
        title: 'Enlazado Interno Estratégico',
        description: 'Desde el blog hacia fichas de producto y categorías.',
        impact: 'Medium',
        status: 'pending',
        category: 'Strategy',
      },
      {
        id: 'e4-3',
        title: 'Prevención de Canibalizaciones',
        description: 'Evitar que post del blog compitan con categorías de venta.',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
    ],
  },
  {
    id: 5,
    title: 'Experiencia de Usuario',
    subtitle: 'UX y Conversión',
    levelRange: '75-85',
    description: 'Mejorar la experiencia para retener y convertir.',
    iconName: 'Activity',
    tasks: [
      {
        id: 'e5-1',
        title: 'Optimización Mobile Commerce',
        description: 'Botones grandes, checkout fácil en móviles.',
        impact: 'High',
        status: 'pending',
        category: 'UX',
      },
      {
        id: 'e5-2',
        title: 'Buscador Interno Optimizado',
        description: "Mejorar resultados de búsqueda interna y analizar 'no results'.",
        impact: 'Medium',
        status: 'pending',
        category: 'UX',
      },
      {
        id: 'e5-3',
        title: 'Compatibilidad de Navegadores',
        description: 'Asegurar que el checkout funciona en todos los navegadores.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 6,
    title: 'Autoridad y Confianza',
    subtitle: 'Reseñas y Seguridad',
    levelRange: '85-95',
    description: 'Factores de confianza para el comprador.',
    iconName: 'Globe',
    tasks: [
      {
        id: 'e6-1',
        title: 'Estrategia de Reseñas (Reviews)',
        description: 'Fomentar valoraciones de usuarios reales.',
        impact: 'High',
        status: 'pending',
        category: 'Authority',
      },
      {
        id: 'e6-2',
        title: 'Google Merchant Center',
        description: 'Optimización del feed de productos para Google Shopping.',
        impact: 'High',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'e6-3',
        title: 'Auditoría de Perfil de Backlinks',
        description: 'Analizar calidad de enlaces entrantes y toxicidad.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'e6-4',
        title: 'Recuperación de Enlaces Perdidos',
        description: 'Contactar sitios que enlazaban a productos ahora 404.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
    ],
  },
  {
    id: 7,
    title: 'Analítica Ecommerce',
    subtitle: 'Medición de Ventas',
    levelRange: '95-100',
    description: 'Datos para toma de decisiones.',
    iconName: 'BarChart3',
    tasks: [
      {
        id: 'e7-1',
        title: 'Configuración GA4 Ecommerce',
        description: 'Medición precisa de ventas, add-to-cart y checkout.',
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
      {
        id: 'e7-2',
        title: 'Análisis de Carritos Abandonados',
        description: 'Identificar fricciones en el proceso de compra.',
        impact: 'Medium',
        status: 'pending',
        category: 'Analytics',
      },
    ],
  },
  {
    id: 8,
    title: 'Extras & Consultas',
    subtitle: 'Acciones Adicionales',
    levelRange: '100+',
    description:
      'Espacio para añadir acciones personalizadas y consultas específicas que surjan durante el proyecto.',
    iconName: 'Sparkles',
    isCustom: true,
    tasks: [],
  },
  MIA_MODULE,
];

export const LOCAL_MODULES: ModuleData[] = [
  {
    id: 1,
    title: 'Presencia Local Básica',
    subtitle: 'Google Business Profile',
    levelRange: '0-20',
    description: 'Configuración fundamental de la ficha de negocio.',
    iconName: 'Search',
    tasks: [
      {
        id: 'l1-1',
        title: 'Reclamar y Verificar GBP',
        description: 'Asegurar la propiedad de la ficha de Google Business Profile.',
        impact: 'High',
        status: 'pending',
        category: 'Local',
      },
      {
        id: 'l1-2',
        title: 'Optimización NAP (Name, Address, Phone)',
        description: 'Consistencia exacta de datos en web y ficha.',
        impact: 'High',
        status: 'pending',
        category: 'Local',
      },
      {
        id: 'l1-3',
        title: 'Selección de Categorías',
        description: 'Elegir categoría principal y secundarias correctas.',
        impact: 'High',
        status: 'pending',
        category: 'Local',
      },
    ],
  },
  {
    id: 2,
    title: 'Web Local Optimizada',
    subtitle: 'Landing Pages Locales',
    levelRange: '20-40',
    description: 'Estructura web para captar tráfico local orgánico.',
    iconName: 'Layers',
    tasks: [
      {
        id: 'l2-1',
        title: 'Páginas de Ubicación (Landing Pages)',
        description: 'Una página por ciudad/sede con contenido único.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'l2-2',
        title: 'Schema LocalBusiness',
        description: 'Marcado de datos estructurados con coordenadas y horarios.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'l2-3',
        title: 'Embed de Google Maps',
        description: 'Incluir mapa interactivo en página de contacto/ubicación.',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'l2-4',
        title: 'Auditoría Técnica Web (404, 301, Canonicals)',
        description: 'Asegurar que la web local es rastreable y sin errores básicos.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'l2-5',
        title: 'Cabeceras de Seguridad',
        description: 'Implementación de seguridad básica (SSL, HSTS).',
        impact: 'Medium',
        status: 'pending',
        category: 'Security',
      },
      {
        id: 'l2-6',
        title: 'Validación W3C y Código',
        description: 'Limpieza de código para asegurar rendimiento.',
        impact: 'Low',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 3,
    title: 'Reputación y Reseñas',
    subtitle: 'Gestión de Opiniones',
    levelRange: '40-60',
    description: 'El factor más influyente en conversión local.',
    iconName: 'BookOpen',
    tasks: [
      {
        id: 'l3-1',
        title: 'Estrategia de Generación de Reseñas',
        description: 'Proceso proactivo para solicitar reseñas a clientes.',
        impact: 'High',
        status: 'pending',
        category: 'Reputation',
      },
      {
        id: 'l3-2',
        title: 'Respuesta a Reseñas',
        description: 'Responder a todas las reseñas (positivas y negativas).',
        impact: 'Medium',
        status: 'pending',
        category: 'Reputation',
      },
    ],
  },
  {
    id: 4,
    title: 'Contenido Local',
    subtitle: 'Relevancia Geográfica',
    levelRange: '60-75',
    description: 'Demostrar conexión con la comunidad.',
    iconName: 'Cpu',
    tasks: [
      {
        id: 'l4-1',
        title: 'Blog con Enfoque Local',
        description: 'Noticias del sector en la ciudad, eventos locales.',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'l4-2',
        title: 'Imágenes Geo-etiquetadas',
        description: 'Fotos reales del negocio y equipo.',
        impact: 'Low',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'l4-3',
        title: 'Prevención de Contenido Duplicado',
        description: 'Asegurar que las landings locales no sean copias exactas.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
    ],
  },
  {
    id: 5,
    title: 'Citaciones y Directorios',
    subtitle: 'Consistencia de Datos',
    levelRange: '75-85',
    description: 'Menciones del negocio en la web.',
    iconName: 'Activity',
    tasks: [
      {
        id: 'l5-1',
        title: 'Directorios Generales y Verticales',
        description: 'Alta en Páginas Amarillas, Yelp y directorios sectoriales.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'l5-2',
        title: 'Limpieza de Citaciones Incorrectas',
        description: 'Corregir teléfonos o direcciones antiguas en la red.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
    ],
  },
  {
    id: 6,
    title: 'Autoridad Local',
    subtitle: 'Enlaces Locales',
    levelRange: '85-95',
    description: 'Backlinks de relevancia geográfica.',
    iconName: 'Globe',
    tasks: [
      {
        id: 'l6-1',
        title: 'Link Building Local',
        description: 'Patrocinios locales, prensa local, asociaciones de comercio.',
        impact: 'High',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'l6-2',
        title: 'Auditoría de Backlinks Locales',
        description: 'Revisar perfil de enlaces y buscar oportunidades de competidores.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
    ],
  },
  {
    id: 7,
    title: 'Medición Local',
    subtitle: 'Insights GBP',
    levelRange: '95-100',
    description: 'Métricas que importan al negocio físico.',
    iconName: 'BarChart3',
    tasks: [
      {
        id: 'l7-1',
        title: 'Monitorización de Llamadas y Rutas',
        description: "Analizar cuántos usuarios piden 'cómo llegar' o llaman.",
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
      {
        id: 'l7-2',
        title: 'Tracking de Ranking Local (Grid)',
        description: 'Ver posición en mapa por zonas de la ciudad.',
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
    ],
  },
  {
    id: 8,
    title: 'Extras & Consultas',
    subtitle: 'Acciones Adicionales',
    levelRange: '100+',
    description:
      'Espacio para añadir acciones personalizadas y consultas específicas que surjan durante el proyecto.',
    iconName: 'Sparkles',
    isCustom: true,
    tasks: [],
  },
  MIA_MODULE,
];

export const NATIONAL_MODULES: ModuleData[] = [
  {
    id: 1,
    title: 'Auditoría Técnica Base',
    subtitle: 'Salud del Sitio',
    levelRange: '0-20',
    description: 'Diagnóstico completo de indexabilidad, rastreo y seguridad.',
    iconName: 'Search',
    tasks: [
      {
        id: 'n1-1',
        title: 'Indexabilidad y Robots.txt',
        description:
          'Verificar directivas de rastreo y asegurar que el contenido clave es indexable.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n1-2',
        title: 'Sitemap XML',
        description: 'Configuración correcta, actualizado y enviado a GSC.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n1-3',
        title: 'Errores de Rastreo (4xx y 5xx)',
        description: 'Identificar y corregir páginas no encontradas y errores de servidor.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n1-4',
        title: 'Redirecciones 3xx y Bucles',
        description: 'Limpieza de cadenas de redirección y enlaces a páginas redirigidas.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n1-5',
        title: 'Canonicals',
        description: 'Implementación correcta de rel=canonical para evitar duplicidad.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n1-6',
        title: 'Cabeceras de Seguridad',
        description: 'HSTS, X-Content-Type-Options y otras cabeceras de seguridad.',
        impact: 'Medium',
        status: 'pending',
        category: 'Security',
      },
    ],
  },
  {
    id: 2,
    title: 'Arquitectura de Información',
    subtitle: 'Estructura y Navegación',
    levelRange: '20-40',
    description: 'Organización del contenido para facilitar el rastreo y la UX.',
    iconName: 'Layers',
    tasks: [
      {
        id: 'n2-1',
        title: 'Estructura de URLs',
        description: 'URLs semánticas, cortas y descriptivas.',
        impact: 'High',
        status: 'pending',
        category: 'Structure',
      },
      {
        id: 'n2-2',
        title: 'Enlazado Interno',
        description: 'Distribución de autoridad y navegación contextual.',
        impact: 'High',
        status: 'pending',
        category: 'Structure',
      },
      {
        id: 'n2-3',
        title: 'Gestión de Paginaciones',
        description: 'Correcta implementación de paginación en listados.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n2-4',
        title: 'Migas de Pan (Breadcrumbs)',
        description: 'Implementación visible y con datos estructurados.',
        impact: 'Medium',
        status: 'pending',
        category: 'Structure',
      },
    ],
  },
  {
    id: 3,
    title: 'Contenido y Semántica',
    subtitle: 'On-Page SEO',
    levelRange: '40-60',
    description: 'Optimización del contenido para relevancia y calidad.',
    iconName: 'BookOpen',
    tasks: [
      {
        id: 'n3-1',
        title: 'Estructura de Encabezados (H1-H6)',
        description: 'Jerarquía lógica y uso de palabras clave en títulos.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'n3-2',
        title: 'Meta Tags (Title & Description)',
        description: 'Optimización para CTR y relevancia.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'n3-3',
        title: 'Contenido Duplicado y Thin Content',
        description: 'Auditoría y resolución de contenido de baja calidad.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'n3-4',
        title: 'Optimización de Imágenes',
        description: 'Atributos ALT, peso y formato (WebP).',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'n3-5',
        title: 'Datos Estructurados (Schema)',
        description: 'Marcado semántico (Organization, Article, Product).',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n3-6',
        title: 'Canibalizaciones SEO',
        description: 'Detección y resolución de páginas compitiendo por la misma keyword.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
    ],
  },
  {
    id: 4,
    title: 'WPO y Renderizado',
    subtitle: 'Rendimiento Técnico',
    levelRange: '60-75',
    description: 'Velocidad de carga y compatibilidad.',
    iconName: 'Cpu',
    tasks: [
      {
        id: 'n4-1',
        title: 'Core Web Vitals',
        description: 'Optimización de LCP, INP y CLS.',
        impact: 'High',
        status: 'pending',
        category: 'WPO',
      },
      {
        id: 'n4-2',
        title: 'Validación HTML5 y Código',
        description: 'Limpieza de errores de sintaxis y validación W3C.',
        impact: 'Low',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n4-3',
        title: 'Compatibilidad Navegadores',
        description: 'Verificar renderizado correcto en diferentes navegadores.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'n4-4',
        title: 'Auditoría de Enlaces Salientes Rotos',
        description: 'Corrección de enlaces externos que dan error.',
        impact: 'Low',
        status: 'pending',
        category: 'Maintenance',
      },
    ],
  },
  {
    id: 5,
    title: 'Autoridad y Enlaces',
    subtitle: 'Off-Page SEO',
    levelRange: '75-90',
    description: 'Estrategia de popularidad y confianza.',
    iconName: 'Globe',
    tasks: [
      {
        id: 'n5-1',
        title: 'Auditoría de Perfil de Backlinks',
        description: 'Análisis de enlaces entrantes y dominios de referencia.',
        impact: 'High',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'n5-2',
        title: 'Análisis de Textos Ancla',
        description: 'Revisión de distribución de anchors para naturalidad.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'n5-3',
        title: 'Identificación de Enlaces Perdidos',
        description: 'Estrategia de recuperación de enlaces valiosos.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'n5-4',
        title: 'Análisis de Competencia',
        description: 'Comparativa de autoridad con competidores del sector.',
        impact: 'Medium',
        status: 'pending',
        category: 'Strategy',
      },
    ],
  },
  {
    id: 6,
    title: 'Analítica y Mejora',
    subtitle: 'Datos y KPIs',
    levelRange: '90-100',
    description: 'Monitorización y optimización continua.',
    iconName: 'BarChart3',
    tasks: [
      {
        id: 'n6-1',
        title: 'Configuración GA4 y GSC',
        description: 'Auditoría de la implementación de herramientas de analítica.',
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
      {
        id: 'n6-2',
        title: 'Dashboard de KPIs',
        description: 'Creación de informes de seguimiento de objetivos.',
        impact: 'Medium',
        status: 'pending',
        category: 'Analytics',
      },
    ],
  },
  {
    id: 7,
    title: 'Extras & Consultas',
    subtitle: 'Acciones Adicionales',
    levelRange: '100+',
    description:
      'Espacio para añadir acciones personalizadas y consultas específicas que surjan durante el proyecto.',
    iconName: 'Sparkles',
    isCustom: true,
    tasks: [],
  },
  MIA_MODULE,
];

export const INTERNATIONAL_MODULES: ModuleData[] = [
  {
    id: 1,
    title: 'Configuración Internacional',
    subtitle: 'Arquitectura Global',
    levelRange: '0-20',
    description: 'Bases técnicas para el posicionamiento en múltiples países/idiomas.',
    iconName: 'Globe',
    tasks: [
      {
        id: 'i1-1',
        title: 'Implementación Hreflang',
        description: 'Etiquetado correcto de idiomas y regiones (alternates).',
        impact: 'High',
        status: 'pending',
        category: 'International',
      },
      {
        id: 'i1-2',
        title: "Auditoría 'Sin Hreflang'",
        description: 'Identificar páginas traducidas a las que les falta la etiqueta.',
        impact: 'High',
        status: 'pending',
        category: 'International',
      },
      {
        id: 'i1-3',
        title: 'Estructura de URLs Internacional',
        description: 'Revisión de estrategia (ccTLD vs subdirectorios vs subdominios).',
        impact: 'High',
        status: 'pending',
        category: 'International',
      },
      {
        id: 'i1-4',
        title: 'Geo-targeting en GSC',
        description: 'Configuración de segmentación internacional en Search Console.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 2,
    title: 'Auditoría Técnica Global',
    subtitle: 'Salud Técnica',
    levelRange: '20-40',
    description: 'Asegurar rastreo e indexación en todos los mercados.',
    iconName: 'Search',
    tasks: [
      {
        id: 'i2-1',
        title: 'Indexabilidad y Sitemaps por Región',
        description: 'Sitemaps específicos o índices de sitemaps correctos.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'i2-2',
        title: 'Errores 4xx y 5xx Globales',
        description: 'Monitorización de errores de respuesta en todos los dominios.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'i2-3',
        title: 'Redirecciones Automáticas (IP)',
        description: 'Verificar que NO se redirija por IP automáticamente (mala práctica Google).',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'i2-4',
        title: 'Canonicals Internacionales',
        description: 'Uso correcto de self-referencing canonicals en cada versión.',
        impact: 'High',
        status: 'pending',
        category: 'Technical',
      },
      {
        id: 'i2-5',
        title: 'Cabeceras de Seguridad',
        description: 'Implementación estándar de seguridad en toda la infraestructura.',
        impact: 'Medium',
        status: 'pending',
        category: 'Security',
      },
    ],
  },
  {
    id: 3,
    title: 'Localización de Contenidos',
    subtitle: 'Calidad y Relevancia',
    levelRange: '40-60',
    description: 'Adaptación cultural y semántica del contenido.',
    iconName: 'BookOpen',
    tasks: [
      {
        id: 'i3-1',
        title: 'Traducción vs Localización',
        description: 'Asegurar que el contenido está adaptado culturalmente, no solo traducido.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'i3-2',
        title: 'Meta Tags Localizados',
        description: 'Titles y descriptions únicos y optimizados por idioma.',
        impact: 'High',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'i3-3',
        title: 'Duplicidad Cross-Language',
        description:
          'Evitar problemas de contenido duplicado entre variantes regionales similares (ej: es-ES vs es-MX).',
        impact: 'Medium',
        status: 'pending',
        category: 'Content',
      },
      {
        id: 'i3-4',
        title: 'Datos Estructurados Localizados',
        description: 'Moneda, dirección y teléfono correctos en Schema local.',
        impact: 'Medium',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 4,
    title: 'WPO e Infraestructura',
    subtitle: 'Rendimiento Global',
    levelRange: '60-75',
    description: 'Velocidad de entrega en diferentes geografías.',
    iconName: 'Cpu',
    tasks: [
      {
        id: 'i4-1',
        title: 'Implementación de CDN',
        description: 'Uso de Content Delivery Network para latencia baja global.',
        impact: 'High',
        status: 'pending',
        category: 'WPO',
      },
      {
        id: 'i4-2',
        title: 'Core Web Vitals por Región',
        description: 'Análisis de velocidad en los mercados objetivo principales.',
        impact: 'High',
        status: 'pending',
        category: 'WPO',
      },
      {
        id: 'i4-3',
        title: 'Validación HTML5 y Código',
        description: 'Estándares web para asegurar compatibilidad global.',
        impact: 'Low',
        status: 'pending',
        category: 'Technical',
      },
    ],
  },
  {
    id: 5,
    title: 'Autoridad Internacional',
    subtitle: 'Off-Page Global',
    levelRange: '75-90',
    description: 'Construcción de relevancia en cada mercado.',
    iconName: 'Globe',
    tasks: [
      {
        id: 'i5-1',
        title: 'Perfil de Backlinks por Mercado',
        description: 'Conseguir enlaces de dominios locales (ccTLDs relevantes).',
        impact: 'High',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'i5-2',
        title: 'Análisis de Textos Ancla',
        description: 'Diversidad de anchors en los idiomas destino.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
      {
        id: 'i5-3',
        title: 'Enlaces Rotos y Perdidos Globales',
        description: 'Auditoría de link juice perdido en todas las versiones.',
        impact: 'Medium',
        status: 'pending',
        category: 'OffPage',
      },
    ],
  },
  {
    id: 6,
    title: 'Analítica Multimercado',
    subtitle: 'Datos Globales',
    levelRange: '90-100',
    description: 'Consolidación de datos para visión global.',
    iconName: 'BarChart3',
    tasks: [
      {
        id: 'i6-1',
        title: 'Configuración GA4 Cross-Domain',
        description: 'Seguimiento correcto de usuarios entre dominios regionales.',
        impact: 'High',
        status: 'pending',
        category: 'Analytics',
      },
      {
        id: 'i6-2',
        title: 'Dashboard Internacional',
        description: 'Vista unificada y desagregada por país/idioma.',
        impact: 'Medium',
        status: 'pending',
        category: 'Analytics',
      },
    ],
  },
  {
    id: 7,
    title: 'Extras & Consultas',
    subtitle: 'Acciones Adicionales',
    levelRange: '100+',
    description:
      'Espacio para añadir acciones personalizadas y consultas específicas que surjan durante el proyecto.',
    iconName: 'Sparkles',
    isCustom: true,
    tasks: [],
  },
  MIA_MODULE,
];

// Alias for backward compatibility
export const INITIAL_MODULES = MEDIA_MODULES;
